[package]
name = "prost-enum"
version = "0.0.0"
license = "MIT"
description = "Enhance serde support for Enums of prost generated files."
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
trybuild = { version = "1.0.49", features = ["diff"] }
