[package]
name = "prost-enum"
version = "0.0.2"
license = "MIT"
description = "Enhance Enums of prost generated files to support serde and sea-orm."
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = "2.0"
sea-orm = { version = "1.0", features = ["macros"], optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prost = "0.13"
trybuild = { version = "1.0", features = ["diff"] }

[features]
default = []
sea-orm = ["dep:sea-orm"]
